-- VHDL Entity UART.address_decode.interface
--
-- Created:
--          by - waly.UNKNOWN (EGC-WALY-LT)
--          at - 00:26:10 09/ 8/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 22 Aug 2022 at 21:00:29
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY address_decode IS
   PORT( 
      -- 3-bit address bus
      addr          : IN     std_logic_vector (2 DOWNTO 0);
      clk           : IN     std_logic;                      -- 10 MHz clock
      rst           : IN     std_logic;                      -- reset(0)
      rst2          : IN     std_logic;
      clk_div_en    : OUT    std_logic;
      clr_int_en    : OUT    std_logic;
      ser_if_select : OUT    std_logic_vector (1 DOWNTO 0);
      xmitdt_en     : OUT    std_logic
   );

-- Declarations

END address_decode ;

--
-- VHDL Architecture UART.address_decode.tbl
--
-- Created:
--          by - waly.UNKNOWN (EGC-WALY-LT)
--          at - 00:26:10 09/ 8/2022
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 22 Aug 2022 at 21:00:29
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF address_decode IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(addr)
   -----------------------------------------------------------------
   BEGIN

      -- Global Actions
      clk_div_en <= '0';
      xmitdt_en <= '0';
      clr_int_en <= '0';
      ser_if_select <= "11";

      -- Block 1
      CASE addr IS
      WHEN "000" =>
         clk_div_en <= '1';
      WHEN "001" =>
         clk_div_en <= '1';
      WHEN "100" =>
         xmitdt_en <= '1';
         ser_if_select <= addr(1 downto 0);
      WHEN "101" =>
         ser_if_select <= addr(1 downto 0);
      WHEN "110" =>
         ser_if_select <= addr(1 downto 0);
      WHEN "111" =>
         clr_int_en <= '1';
      WHEN OTHERS =>
         clk_div_en <= '0';
         xmitdt_en <= '0';
         ser_if_select <= "11";
         clr_int_en <= '0';
      END CASE;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
