-- VHDL Entity UART.cpu_interface.interface
--
-- Created:
--          by - JSmith.UNKNOWN (EGC-WALY-LT)
--          at - 11:25:03 10/03/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 22 Aug 2022 at 21:00:29
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY cpu_interface IS
   PORT( 
      clk          : IN     std_logic;                      -- 10 MHz clock
      clk_div_en   : IN     std_logic;
      clr_int_en   : IN     std_logic;
      cs           : IN     std_logic;                      -- chip select
      div_data     : IN     std_logic_vector (7 DOWNTO 0);
      nrw          : IN     std_logic;                      -- r(0), w(1)
      rst          : IN     std_logic;                      -- reset(0)
      ser_if_data  : IN     std_logic_vector (7 DOWNTO 0);
      xmitdt_en    : IN     std_logic;
      clear_flags  : OUT    std_logic;
      datout       : OUT    std_logic_vector (7 DOWNTO 0);  -- data to cpu
      enable_write : OUT    std_logic;
      start_xmit   : OUT    std_logic
   );

-- Declarations

END cpu_interface ;

--
-- VHDL Architecture UART.cpu_interface.struct
--
-- Created:
--          by - JSmith.UNKNOWN (EGC-WALY-LT)
--          at - 11:24:53 10/03/2019
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 22 Aug 2022 at 21:00:29
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY UART;

ARCHITECTURE struct OF cpu_interface IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT control_operation
   PORT (
      clk          : IN     std_logic ;
      clr_int_en   : IN     std_logic ;
      cs           : IN     std_logic ;
      nrw          : IN     std_logic ;
      rst          : IN     std_logic ;
      xmitdt_en    : IN     std_logic ;
      clear_flags  : OUT    std_logic ;
      enable_write : OUT    std_logic ;
      start_xmit   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : control_operation USE ENTITY UART.control_operation;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 data_out_mux
   datout <= div_data WHEN clk_div_en = '1' ELSE
                      ser_if_data;


   -- Instance port mappings.
   U_0 : control_operation
      PORT MAP (
         clk          => clk,
         clr_int_en   => clr_int_en,
         cs           => cs,
         nrw          => nrw,
         rst          => rst,
         xmitdt_en    => xmitdt_en,
         clear_flags  => clear_flags,
         enable_write => enable_write,
         start_xmit   => start_xmit
      );

END struct;
